### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by calderon** [Angoll/KPass#22] opened 2022-01-14 12:11 UTC
First of all, thanks for taking your time to develop something so useful.

Sadly, I've been trying to make it work, unsuccessful. I'm not really sure if I'm doing something bad. I have my password database on Google Drive. After writing kpass on Alfred, KpassLoader appears and after a while, dissapear. But after that, if I write something (like twitter, gmail, whatever) to find out the password, nothing happens. Could you help? It would be SO nice to make it work. Thanks.

**Comment by toitzi** [comment] 2022-02-28 15:09
I got the same problem, have you solved it yet?

**Comment by Angoll** [comment] 2022-03-18 23:06
Hello, I would need more information on what is happening. Give 2.4 version a try I fixed some of the issues regarding paths, and could be that.

**Comment by wolasss** [comment] 2022-04-29 11:58
I can confirm - it does not work for me either. I tried version 2.5, I have keepassxc 2.7.0 installed. It seems to be logging the database correctly, but there are no results being shown, I noticed that before I start typing any query it shows a merged list of my entries from the database

**Comment by wolasss** [comment] 2022-10-17 17:27
Finally I had some time to debug this issue. It seems there is a bug in get_db_keys function for people who don't use `keePassKeyFile`: https://github.com/Angoll/KPass/blob/fb7a7ddea6fe9ff1621244835216d6e73b3111ab/scripts/listDatabase.sh#L9

I noticed `-q` cannot be passed if password is piped to keepassxc-cli. When I removed this param it started to work as intended.

**Comment by Angoll** [comment] 2022-11-12 17:33
hello @wolasss  I could not reproduce it, but I removed the -q in the v2.6.

**Closed as completed by Angoll** 2022-11-12 17:33 UTC
